### ISSUE TITLE
Correct Subheadings

### ISSUE THREAD

**Issue by nikhilweee** [offconvex/offconvex.github.io#5]
Forgive me if I'm being too picky, but there must be an additional space between the `#` and the `P` characters for the headings to render properly.
https://github.com/offconvex/offconvex.github.io/blob/b5fd7a1cf5bc3c73bece69d99ff74caae4916f63/_posts/2015-12-12-word-embeddings-1.md#L22
The above should instead be corrected to the following.
```markdown
 ## Properties of Word Embeddings 
```
So is the issue with the other subheading in the same post. 
https://github.com/offconvex/offconvex.github.io/blob/b5fd7a1cf5bc3c73bece69d99ff74caae4916f63/_posts/2015-12-12-word-embeddings-1.md#L54

**Comment by cohennadav** [comment]
Fixed, thanks!
